### ISSUE TITLE
Can't upload media files in docker install

### ISSUE THREAD

**Issue by tgly307** [RestyaPlatform/board#2281]
I follow the [guide](https://github.com/RestyaPlatform/board/wiki/Docker:-Build-and-Install) to install using docker, and it works for new install.

But I want to save the volume in a local folder, just use below `docker-compose.yml`.
```
version: '2'
services:
  restyaboard:
    image: restyaplatform/restyaboard:dev
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      SMTP_DOMAIN: domain
      SMTP_USERNAME: user
      SMTP_PASSWORD: pass
      SMTP_SERVER: server
      SMTP_PORT: 465
      TZ: Etc/UTC
    volumes:
    - /root/restyaboard/media:/usr/share/nginx/html/media
    ports:
    - "8081:80"
  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
    - /root/restyaboard/db:/var/lib/postgresql/data
```
This will start normally, but no files will be written in the media folder. 
The default avatar failed to load, and uploading the avatar and uploading the attachment failed.
I guess this is a docker permission question, where do I need to set it?

## Your Environment
* Version used: 0.6.6
* Environment name and version (e.g. OS, PHP, PostgreSQL): centOS7 64bit, Docker version 1.13.1, postgres9-alpine
