### ISSUE TITLE
Nginx error about FastCGI

### ISSUE THREAD

**Issue by ishbguy** [RestyaPlatform/board#2576]
<!--- 
  Please don't get offended with below. If you find it too much for you, please feel free to remove all and submit your content.
  We always welcome bug report in any format. This is merely an effort to enforce good practices.
  
  For issues about installations, please always attach restyaboard_install.log, after removing any sensitive data. You may also request free installation support http://restya.com/contact?category=free-installation
-->


<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

Restyaboard run fluently when access by browser.

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

Pages refresh slowly and sometimes broken.



`docker logs restyaboard_restyaboard1` output:

```
==> /var/log/nginx/error.log <==
2019/04/29 20:02:47 [error] 146#146: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(/usr/share/nginx/html/tmp/cache/site_url_for_shell.php): failed to open stream: No such file or directory in /usr/share/nginx/html/server/php/config.inc.php on line 66
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 67
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 68
PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 69
PHP message: PHP Warning:  fopen(/usr/share/nginx/html/tmp/cache/client_information.php): failed to open stream: No such file or directory in /usr/share/nginx/html/server/php/bootstrap.php on line 52
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/bootstrap.php on line 53
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/bootstrap.php on line 54
PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/bootstrap.php on line 55" while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET /api/v1/oauth.json?_=1556539364105 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "localhost:1234", referrer: "http://localhost:1234/"
```

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

Create /usr/share/nginx/html/tmp/cache/ in restyaboard container:

```
docker exec -it restyaboard bash
mkdir /usr/share/nginx/html/tmp/cache -p
chown -R www-data:www-data /usr/share/nginx/html/tmp/
```

Or add copy instruction after copy media dir in Dockerfile then rebuild image:

```
COPY tmp/ tmp/
```

## Docker infos:

Docker image ID: `badccc0da73a` from restyaplatform/restyaboard docker hub.

docker-compose.yml:

```
version: '2' 
volumes:   
  restyaboard_db:
    driver: local
  restyaboard_media:
    driver: local
services:  
  restyaboard:
    image: restyaplatform/restyaboard:dev
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      SMTP_DOMAIN: domain
      SMTP_USERNAME: user
      SMTP_PASSWORD: pass
      SMTP_SERVER: server
      SMTP_PORT: 465 
      TZ: Asia/Shanghai
    volumes:
      - restyaboard_media:/usr/share/nginx/html/media
    ports: 
      - "1234:80"
  postgres:                                                                                                                                                                                                                                    
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - restyaboard_db:/var/lib/postgresql/data
```
