### ISSUE TITLE
SMTP Notification not working, email on demand (e.g. user verification) works

### ISSUE THREAD

**Issue by dhaeb** [RestyaPlatform/board#2738]
We are using restya version 0.6.7, especially the image from docker hub. We were able to setup SMTP server connection using the Docker parameter:

```
###...
  app:
    image: restyaplatform/restyaboard:v0.6.7
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      SMTP_DOMAIN: ourdomain.com
      SMTP_USERNAME: rbreply@ourdomain.com # valid credentials at the SMTP server
      SMTP_PASSWORD: thepw
      SMTP_SERVER: serverdomain.com
      SMTP_PORT: 465
      TZ: Etc/UTC

```
The SMTP connection works. We are able to send emails on manual request, for example when adding a new user and sending him a validation email. We also used the SMTP client mail to ensure, that emails can be send using postfix. Our postfix is well configured and functional.

## Expected Behavior

The problem starts to arise when using notifications. 
Normally, when activating notification for a user in your profile settings, you expect emails every hour / or five minutes for every action performed in your subscribed boards / tickets etc. 

## Current Behavior

However, currently no notifcations are sent, despite the correct SMTP configurations.
## Possible Solution

Those notfications are implemented in Restya using CRON services / scripts. I was able to bring notifications to work by adjusting my crontab:

```
*/5 * * * * /usr/share/nginx/html/server/php/shell/instant_email_notification.sh
0 * * * * /usr/share/nginx/html/server/php/shell/periodic_email_notification.sh
*/30 * * * * /usr/share/nginx/html/server/php/shell/imap.sh
*/5 * * * * /usr/share/nginx/html/server/php/shell/webhook.sh
*/5 * * * * /usr/share/nginx/html/server/php/shell/card_due_notification.sh
```
It seems like that the referenced scripts in crontab are not existing:

```
# pwd
/usr/share/nginx/html/server/php/shell
# ls -la
total 140
drwxr-xr-x. 1 www-data www-data  4096 Jul 24 12:49 .
drwxr-xr-x. 1 www-data www-data  4096 Jul 24 08:00 ..
-rw-r--r--. 1 www-data www-data  3879 Apr 24 15:05 card_due_notification.php
-rw-r--r--. 1 www-data www-data  2028 Apr 24 15:05 cron_mail.php
-rw-r--r--. 1 www-data www-data 22149 Apr 24 15:05 imap.php
-rw-r--r--. 1 www-data www-data 33615 Apr 24 15:05 instant_email_notification.php
-rw-r--r--. 1 www-data www-data   901 Apr 24 15:05 main.php
-rwxr-xr-x. 1 www-data www-data   867 Apr 24 15:05 main.sh
-rw-r--r--. 1 www-data www-data 35886 Apr 24 15:05 periodic_email_notification.php
-rw-r--r--. 1 www-data www-data  4479 Apr 24 15:05 webhook.php
```
 Can you clearify, why does scripts are not there? 
BTW when executing the main.sh file, the notifications are sent. So I think that you forgot to update the crontab file in your Dockerfile. 

## Steps to Reproduce (for bugs)

0. Ensure you got a working SMTP server with a SMTP user you control
1. Start Restya via docker (compose) and configure the SMTP credentials:
```
version: '3'

services:
  postgres:
    image: postgres:9-alpine
    networks:
      - default
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
    - restyaboard_db:/var/lib/postgresql/data

  app:
    image: restyaplatform/restyaboard:v0.6.7
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      SMTP_DOMAIN: mydomain.com # change
      SMTP_USERNAME: rbreply@mydomain.com # change
      SMTP_PASSWORD: mypass # change
      SMTP_SERVER: mydomain.com # change
      SMTP_PORT: 465 # change
      TZ: Etc/UTC
    volumes:
    - restyaboard_media:/usr/share/nginx/html/media
    networks:
      - default
      - proxy-net


volumes:
  restyaboard_db:
    driver: local
  restyaboard_media:
    driver: local

networks:
  proxy-net:
    external: true

```
2. Ensure, postfix is working [bsd-mailx](https://wiki.ubuntuusers.de/Postfix/) for testing purposes on the container, try to send a mail using "mail"
3. Enable notifications in Restya board and subscribe to a board 
4. You don't will get any notifcation by restya. To get notifications, you can execute the file 
```
/usr/share/nginx/html/server/php/shell
```

## Context

Getting notification via SMTP. 
## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:
Docker / CentOS 7.0 / Restya 0.6.7

## Related issues
Feature request for SMTP config in the application: #2734
Our used workaround mentioned in: #450
Handle to crontab: #1133 
Weired "to" behaviour: #1145
