### ISSUE TITLE
Docker Compose Example Appears Incomplete

### ISSUE THREAD

**Issue by shawnweeks** [RestyaPlatform/board#4030]
Using the example docker-compose.yml at https://github.com/RestyaPlatform/board/wiki/Docker:-Build-and-Install Restya complains about the following variables missing and once they are provided it then complains about the database "admin" not existing despite specifying POSTGRES_DB. It appears that a better docker-compose.yml is in the repo though.

POSTGRES_ADMIN_PASS
POSTGRES_ADMIN_USER
RESTYA_DB_USERNAME
RESTYA_DB_USERPASS

Here is my docker-compose.yml

```
version: '2'
volumes:
  restyaboard_db:
    driver: local
  restyaboard_media:
    driver: local
services:
  restyaboard:
    image: restyaplatform/restyaboard:dev
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_ADMIN_PASS: admin
      POSTGRES_ADMIN_USER: admin
      RESTYA_DB_USERNAME: admin
      RESTYA_DB_USERPASS: admin
      SMTP_DOMAIN: domain
      SMTP_USERNAME: user
      SMTP_PASSWORD: pass
      SMTP_SERVER: server
      SMTP_PORT: 465
      TZ: Etc/UTC
    volumes:
    - restyaboard_media:/usr/share/nginx/html/media
    ports:
    - "8081:80"
  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: restyaboard
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
    - restyaboard_db:/var/lib/postgresql/data
```

```
Recreating docker-restyaboard_restyaboard_1 ... done
Starting docker-restyaboard_postgres_1      ... done
Attaching to docker-restyaboard_postgres_1, docker-restyaboard_restyaboard_1
postgres_1     | 
postgres_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1     | 
restyaboard_1  | Starting restya ...
postgres_1     | LOG:  database system was shut down at 2020-04-21 15:39:43 UTC
restyaboard_1  | Trying to connect to postgres ...
restyaboard_1  | postgres:5432 - accepting connections
postgres_1     | LOG:  MultiXact member wraparound protections are now enabled
restyaboard_1  | Connection established!
postgres_1     | LOG:  autovacuum launcher started
postgres_1     | LOG:  database system is ready to accept connections
postgres_1     | FATAL:  database "admin" does not exist
postgres_1     | FATAL:  database "admin" does not exist
restyaboard_1  | psql: error: could not connect to server: FATAL:  database "admin" does not exist
restyaboard_1  | Creating PostgreSQL user and database...
postgres_1     | FATAL:  database "admin" does not exist
restyaboard_1  | psql: error: could not connect to server: FATAL:  database "admin" does not exist
restyaboard_1  | PostgreSQL user creation failed with error code 2 (PostgreSQL user creation failed with error code 35)
restyaboard_1  | Failed to initialize DB for restyaboard.
docker-restyaboard_restyaboard_1 exited with code 1
```
