### ISSUE TITLE
Docker compose example fails to start on v0.6.8

### ISSUE THREAD

**Issue by cdhowie** [RestyaPlatform/board#4042]
This seems similar to #4030 but the error message is slightly different.

## Expected Behavior
When using the example `docker-compose.prod.yml` file, the container should start without error.

## Current Behavior
The restyaboard container tries to authenticate to the database as the user `admin` (despite no such user being configured in the compose file).

## Logs:
```
restyaboard_1  | psql: FATAL:  password authentication failed for user "admin"
```

## Compose file:
```
version: "2"
services:
  restyaboard:
    image: restyaplatform/restyaboard:v0.6.8
    volumes:
      - ./media:/usr/share/nginx/html/media
    ports:
      - 127.0.0.1:8080:80
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASS=admin
      - RESTYA_DB_USERNAME=restya
      - RESTYA_DB_USERPASS=restya
      #- RESTYA_DB=restyaboard
      #- SMTP_SERVER=smtp_relay
      #- SMTP_PORT=587
      - TZ=America/Indiana/Indianapolis
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always
```

Note that `admin` appears nowhere as a database username.

## Your Environment

* Version used: 0.6.8
* Environment name and version (e.g. OS, PHP, PostgreSQL): Whatever is provided by the Docker images given in the example.
* Operating System and version (desktop or mobile): Debian 10
