### ISSUE TITLE
Database is not persistent in production deployment 

### ISSUE THREAD

**Issue by danielwilson654** [RestyaPlatform/board#4220]
https://github.com/RestyaPlatform/board/blob/dev/docker-compose.prod.yml

Hello! I noticed there is no volume mapping to the database container in the production compose file. This means if the host restarts, all data is lost. Is this intended? I added the following to the docker-compose.yml file.

```
...
 postgres:
    image: postgres:12-alpine
    volumes:
      - /var/opt/restya/data:/var/lib/postgresql/data #Make data persistent
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    restart: always

```
