### ISSUE TITLE
Cannot save user details on minimal docker setup

### ISSUE THREAD

**Issue by draotth** [RestyaPlatform/board#4401]
## Expected Behavior

Can save user settings on default restya board install in Docker.

## Current Behavior

Cannot save settings (no error shown in UI)

## Steps to Reproduce (for bugs)

1. Setup default docker with docker-compose.
2. Access website, most things work.
3. Try to update default admin user settings (any setting).
4. Settings are not saved but no end-user facing error.

Note, postgres docker container shows this in log:
```
postgres_1     | 2022-04-06 12:27:03.905 EDT [62] ERROR:  must be owner of extension plpgsql
postgres_1     | 2022-04-06 12:27:03.905 EDT [62] STATEMENT:  COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
postgres_1     | 2022-04-06 12:27:39.133 EDT [75] ERROR:  relation "user_push_tokens" does not exist at character 58
postgres_1     | 2022-04-06 12:27:39.133 EDT [75] STATEMENT:  SELECT id,device_modal,last_push_notified,is_active FROM user_push_tokens WHERE user_id = $1 ORDER BY id DESC
```

Completely wiped all docker images/volumes and restarted:
Restyaboard log:
```
restyaboard_1  | Starting restya ...
restyaboard_1  | Trying to connect to postgres ...
restyaboard_1  | postgres:5432 - rejecting connections
restyaboard_1  | Trying to connect to postgres ...
restyaboard_1  | postgres:5432 - accepting connections
restyaboard_1  | Connection established!
restyaboard_1  | Creating PostgreSQL user and database...
restyaboard_1  | NOTICE:  role "restya" does not exist, skipping
restyaboard_1  | CREATE ROLE
restyaboard_1  | CREATE DATABASE
restyaboard_1  | NOTICE:  extension "plpgsql" already exists, skipping
restyaboard_1  | CREATE EXTENSION
restyaboard_1  | COMMENT
restyaboard_1  | Importing empty SQL... (pipe output to /tmp/restya_initdb.log)
restyaboard_1  | psql:/var/lib/nginx/html/sql/restyaboard_with_empty_data.sql:30: ERROR:  must be owner of extension plpgsql
restyaboard_1  | Succesfully imported initial data.
```

## Your Environment

* Version used: Latest docker images
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile): Ubuntu hosting docker.
* Link to your project:

My `docker-compose.yml`
```
version: "2"
services:
  restyaboard:
    image: restyaplatform/restyaboard:dev
    expose:
      - "80"
    networks:
      - traefik
    volumes:
      - /var/opt/restya/media:/var/lib/nginx/html/media
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASS=admin
      - RESTYA_DB_USERNAME=restya
      - RESTYA_DB_USERPASS=restya
      - RESTYA_DB=restyaboard
      - SMTP_SERVER=smtp_relay
      - SMTP_PORT=1587
      - TZ=America/Detroit
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:12-alpine
    networks:
      - traefik
    volumes:
      - /var/opt/restya/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - TZ=America/Detroit
    restart: unless-stopped

networks:
  traefik:
    external: true

```
